import { notifyComponentLoaded } from "@hzero-front-ui/core/lib/utils/dynamicLoad";
import "../Collapse/css";
import "../SpinPro/css";
import "../PaginationPro/css";
import "../Tag/css";
import "../ModalPro/css";
import "../FormPro/css";
import "../TooltipPro/css";
import "../OutputPro/css";
import "../ButtonPro/css";
import "../SwitchPro/css";
import "../RadioPro/css";
import "../MenuPro/css";
import "../CheckBoxPro/css";
import "../DropdownPro/css";
import "../TextFieldPro/css";
import "../SecretFieldPro/css";
import "../ColorPickerPro/css";
import "../AttachmentPro/css";
import "../CurrencyPro/css";
import "../NumberFieldPro/css";
import "../IntlFieldPro/css";
import "../UrlFieldPro/css";
import "../EmailFieldPro/css";
import "../LovPro/css";
import "../SelectPro/css";
import "../SelectBoxPro/css";
import "../TreeSelectPro/css";
import "../DatePickerPro/css";

notifyComponentLoaded("choerodon-ui::tablePro");
