module.exports = {
  name: "pro-table",
  apis: [
    {
      name: "get",
      url: "/hpfm/v1/0/search-config",
      method: "get",
      handle() {
        return {
          status: 200,
          data: [
            {
              creationDate: "2021-03-08 20:05:57",
              createdBy: 2,
              lastUpdateDate: "2021-03-08 20:05:57",
              lastUpdatedBy: 2,
              objectVersionNumber: 1,
              _token:
                "/uqs6jADKr9uFI6IYFiUG9ROIiBf3WizlgZV+wyc45tbl9D0aOrr3Je4wXVaaO6zSo7aROWRvMMep9Q26yP1H8bE3B1iZfWfy99we8hSJH3cA1pWLxNzOhzK39RMaBTa",
              searchId: 34,
              searchCode: "test",
              searchName: "tyfuy",
              defaultFlag: 1,
              remark: null,
              userId: 2,
              tenantId: 0,
              conditionList: [
                {
                  creationDate: "2021-03-08 20:05:57",
                  createdBy: 2,
                  lastUpdateDate: "2021-03-08 20:05:57",
                  lastUpdatedBy: 2,
                  objectVersionNumber: 1,
                  _token:
                    "/uqs6jADKr9uFI6IYFiUG9ROIiBf3WizlgZV+wyc45tbl9D0aOrr3Je4wXVaaO6zSo7aROWRvMMep9Q26yP1H9wAllcoC37WDzWCEECwWe8cPKHwwpJCt+ISDmD69nv01uzJHDl/Vim4g8gY2A7hlA==",
                  searchConditionId: 16,
                  searchId: 34,
                  fieldName: "email",
                  comparator: "EQUAL",
                  value: "dsfasd",
                  tenantId: 0,
                },
                {
                  creationDate: "2021-03-08 20:05:57",
                  createdBy: 2,
                  lastUpdateDate: "2021-03-08 20:05:57",
                  lastUpdatedBy: 2,
                  objectVersionNumber: 1,
                  _token:
                    "/uqs6jADKr9uFI6IYFiUG9ROIiBf3WizlgZV+wyc45tbl9D0aOrr3Je4wXVaaO6zSo7aROWRvMMep9Q26yP1H9wAllcoC37WDzWCEECwWe8cPKHwwpJCt+ISDmD69nv0Fn6c2T6NuPGGhrdguWcLbw==",
                  searchConditionId: 17,
                  searchId: 34,
                  fieldName: "state",
                  comparator: "EQUAL",
                  value: "CODE_2",
                  tenantId: 0,
                },
                {
                  creationDate: "2021-03-08 20:05:57",
                  createdBy: 2,
                  lastUpdateDate: "2021-03-08 20:05:57",
                  lastUpdatedBy: 2,
                  objectVersionNumber: 1,
                  _token:
                    "/uqs6jADKr9uFI6IYFiUG9ROIiBf3WizlgZV+wyc45tbl9D0aOrr3Je4wXVaaO6zSo7aROWRvMMep9Q26yP1H9wAllcoC37WDzWCEECwWe8cPKHwwpJCt+ISDmD69nv077uePy/QZTkfXH4B9yyF0w==",
                  searchConditionId: 18,
                  searchId: 34,
                  fieldName: "taskDescription",
                  comparator: "EQUAL",
                  value: "sss",
                  tenantId: 0,
                },
              ],
              queryList: [],
              orderList: [],
            },
            {
              creationDate: "2021-01-10 15:02:51",
              createdBy: 2,
              lastUpdateDate: "2021-01-11 15:27:05",
              lastUpdatedBy: 2,
              objectVersionNumber: 5,
              _token:
                "/uqs6jADKr9uFI6IYFiUG9ROIiBf3WizlgZV+wyc45tbl9D0aOrr3Je4wXVaaO6zSo7aROWRvMMep9Q26yP1HxR9kcfiTEgSYnPEppGb6CjcA1pWLxNzOhzK39RMaBTa",
              searchId: 33,
              searchCode: "test",
              searchName: "1234567890",
              defaultFlag: 0,
              remark: null,
              userId: 2,
              tenantId: 0,
              conditionList: [
                {
                  creationDate: "2021-01-10 15:02:51",
                  createdBy: 2,
                  lastUpdateDate: "2021-01-10 15:02:51",
                  lastUpdatedBy: 2,
                  objectVersionNumber: 1,
                  _token:
                    "/uqs6jADKr9uFI6IYFiUG9ROIiBf3WizlgZV+wyc45tbl9D0aOrr3Je4wXVaaO6zSo7aROWRvMMep9Q26yP1H9wAllcoC37WDzWCEECwWe8cPKHwwpJCt+ISDmD69nv0SQOqw7MZLwHezz3G+ZbD3g==",
                  searchConditionId: 13,
                  searchId: 33,
                  fieldName: "state",
                  comparator: "EQUAL",
                  value: "CODE_1",
                  tenantId: 0,
                },
                {
                  creationDate: "2021-01-10 15:02:51",
                  createdBy: 2,
                  lastUpdateDate: "2021-01-10 15:02:51",
                  lastUpdatedBy: 2,
                  objectVersionNumber: 1,
                  _token:
                    "/uqs6jADKr9uFI6IYFiUG9ROIiBf3WizlgZV+wyc45tbl9D0aOrr3Je4wXVaaO6zSo7aROWRvMMep9Q26yP1H9wAllcoC37WDzWCEECwWe8cPKHwwpJCt+ISDmD69nv0t9zkRCZ9cBR8bR0oQWapGw==",
                  searchConditionId: 14,
                  searchId: 33,
                  fieldName: "taskNumber",
                  comparator: "EQUAL",
                  value: "2",
                  tenantId: 0,
                },
              ],
              queryList: [],
              orderList: [],
            },
            {
              creationDate: "2021-01-10 14:51:53",
              createdBy: 2,
              lastUpdateDate: "2021-03-08 20:05:57",
              lastUpdatedBy: 2,
              objectVersionNumber: 14,
              _token:
                "/uqs6jADKr9uFI6IYFiUG9ROIiBf3WizlgZV+wyc45tbl9D0aOrr3Je4wXVaaO6zSo7aROWRvMMep9Q26yP1H/dwcaisTe10CiHJgVB0MJDcA1pWLxNzOhzK39RMaBTa",
              searchId: 31,
              searchCode: "test",
              searchName: "111",
              defaultFlag: 0,
              remark: null,
              userId: 2,
              tenantId: 0,
              conditionList: [
                {
                  creationDate: "2021-01-10 14:51:53",
                  createdBy: 2,
                  lastUpdateDate: "2021-01-18 16:17:41",
                  lastUpdatedBy: 2,
                  objectVersionNumber: 6,
                  _token:
                    "/uqs6jADKr9uFI6IYFiUG9ROIiBf3WizlgZV+wyc45tbl9D0aOrr3Je4wXVaaO6zSo7aROWRvMMep9Q26yP1H9wAllcoC37WDzWCEECwWe8cPKHwwpJCt+ISDmD69nv0uhccMumJT7Y7CSheCteNZQ==",
                  searchConditionId: 10,
                  searchId: 31,
                  fieldName: "state",
                  comparator: "EQUAL",
                  value: "CODE_2",
                  tenantId: 0,
                },
                {
                  creationDate: "2021-01-18 16:17:41",
                  createdBy: 2,
                  lastUpdateDate: "2021-01-18 16:17:41",
                  lastUpdatedBy: 2,
                  objectVersionNumber: 1,
                  _token:
                    "/uqs6jADKr9uFI6IYFiUG9ROIiBf3WizlgZV+wyc45tbl9D0aOrr3Je4wXVaaO6zSo7aROWRvMMep9Q26yP1H9wAllcoC37WDzWCEECwWe8cPKHwwpJCt+ISDmD69nv0mEE51Eepclhsjn8gFM181Q==",
                  searchConditionId: 15,
                  searchId: 31,
                  fieldName: "taskDescription",
                  comparator: "EQUAL",
                  value: "sss",
                  tenantId: 0,
                },
                {
                  creationDate: "2021-01-10 14:51:53",
                  createdBy: 2,
                  lastUpdateDate: "2021-01-18 16:17:41",
                  lastUpdatedBy: 2,
                  objectVersionNumber: 6,
                  _token:
                    "/uqs6jADKr9uFI6IYFiUG9ROIiBf3WizlgZV+wyc45tbl9D0aOrr3Je4wXVaaO6zSo7aROWRvMMep9Q26yP1H9wAllcoC37WDzWCEECwWe8cPKHwwpJCt+ISDmD69nv0dlJauhGpw4+TUxM8tJXlUQ==",
                  searchConditionId: 9,
                  searchId: 31,
                  fieldName: "taskNumber",
                  comparator: "EQUAL",
                  value: "0",
                  tenantId: 0,
                },
              ],
              queryList: [],
              orderList: [],
            },
          ],
        };
      },
    },
    {
      name: "post",
      url: "/sys/lov/lov_define",
      method: "post",
      handle() {
        return {
          status: 200,
          data: {
            _token: "@guid()",
            objectVersionNumber: 1,
            code: "LOV_CODE",
            description: "快码",
            height: 300,
            lovId: 10015,
            lovItems: [
              {
                _token: "@guid()",
                objectVersionNumber: 1,
                lovItemId: 10033,
                lovId: 10015,
                display: "租户编号",
                gridFieldName: "code",
                gridFieldWidth: 150,
                gridFieldAlign: "left",
                autocompleteField: "Y",
                conditionField: "Y",
                isAutocomplete: "N",
                gridField: "Y",
                conditionFieldWidth: null,
                conditionFieldLabelWidth: null,
                conditionFieldType: null,
                conditionFieldName: null,
                conditionFieldTextfield: null,
                conditionFieldNewline: "N",
                conditionFieldSelectUrl: null,
                conditionFieldSelectVf: null,
                conditionFieldSelectTf: null,
                conditionFieldSelectCode: null,
                conditionFieldLovCode: null,
                conditionFieldSequence: 1,
                gridFieldSequence: 1,
              },
              {
                _token: "@guid()",
                objectVersionNumber: 1,
                lovItemId: 10034,
                lovId: 10015,
                display: "租户名称",
                gridFieldName: "description",
                gridFieldWidth: 250,
                gridFieldAlign: "left",
                autocompleteField: "Y",
                conditionField: "Y",
                isAutocomplete: "N",
                gridField: "Y",
                conditionFieldWidth: null,
                conditionFieldLabelWidth: null,
                conditionFieldType: null,
                conditionFieldName: null,
                conditionFieldTextfield: null,
                conditionFieldNewline: "N",
                conditionFieldSelectUrl: null,
                conditionFieldSelectVf: null,
                conditionFieldSelectTf: null,
                conditionFieldSelectCode: null,
                conditionFieldLovCode: null,
                conditionFieldSequence: 2,
                gridFieldSequence: 2,
              },
            ],
            sqlId: "CodeMapper.select",
            customSql: null,
            queryColumns: 2,
            customUrl: null,
            textField: "description",
            title: "选择租户",
            valueField: "code",
            width: 710,
            delayLoad: "N",
            needQueryParam: "N",
            editableFlag: "N",
            canPopup: "Y",
            lovPageSize: "10",
            treeFlag: "N",
            idField: null,
            parentIdField: null,
          },
        };
      },
    },
    {
      name: "p",
      url: "/dataset/common/lov/dataset/LOV_CODE",
      method: "post",
      handle() {
        return {
          status: 200,
          data: [
            {
              _token: "5fd2371f43d3c75c44682b0750e7bfb5",
              objectVersionNumber: 2,
              code: "HR.EMPLOYEE_GENDER",
              codeId: 10001,
              codeValues: null,
              description: "租户1",
              type: "USER",
              enabledFlag: "Y",
              parentCodeId: null,
              parentCodeDescription: null,
            },
            {
              _token: "d8f3d1a86b47be97d570220f09f9da70",
              objectVersionNumber: 1,
              code: "HR.EMPLOYEE_STATUS",
              codeId: 10002,
              codeValues: null,
              description: "租户2",
              type: "USER",
              enabledFlag: "Y",
              parentCodeId: null,
              parentCodeDescription: null,
            },
            {
              _token: "fef2a3f782a4aef3f550590981f54b11",
              objectVersionNumber: 1,
              code: "SYS.ALIGN_TYPE",
              codeId: 10003,
              codeValues: null,
              description: "租户3",
              type: "USER",
              enabledFlag: "Y",
              parentCodeId: null,
              parentCodeDescription: null,
            },
            {
              _token: "f2d56a73573733af27b46d981771f692",
              objectVersionNumber: 1,
              code: "SYS.CAPTCHA_POLICY",
              codeId: 10004,
              codeValues: null,
              description: "租户4",
              type: "USER",
              enabledFlag: "Y",
              parentCodeId: null,
              parentCodeDescription: null,
            },
            {
              _token: "690beb6510bccb2eeb906c736f7cfdc9",
              objectVersionNumber: 1,
              code: "SYS.LOV_EDITOR_TYPE",
              codeId: 10005,
              codeValues: null,
              description: "租户5",
              type: "USER",
              enabledFlag: "Y",
              parentCodeId: null,
              parentCodeDescription: null,
            },
            {
              _token: "1d600f30fa2bfbf98061c8a3cb9a7c6c",
              objectVersionNumber: 1,
              code: "SYS.PRIORITY_LEVEL",
              codeId: 10006,
              codeValues: null,
              description: "租户6",
              type: "USER",
              enabledFlag: "Y",
              parentCodeId: null,
              parentCodeDescription: null,
            },
            {
              _token: "457a1217cc9343c41d41d5de1e2d6f1e",
              objectVersionNumber: 1,
              code: "SYS.PROFILE_LEVEL_ID",
              codeId: 10007,
              codeValues: null,
              description: "租户7",
              type: "USER",
              enabledFlag: "Y",
              parentCodeId: null,
              parentCodeDescription: null,
            },
            {
              _token: "50f8dd1303a2c82557246dc296cc9d94",
              objectVersionNumber: 1,
              code: "SYS.RESOURCE_TYPE",
              codeId: 10008,
              codeValues: null,
              description: "租户8",
              type: "USER",
              enabledFlag: "Y",
              parentCodeId: null,
              parentCodeDescription: null,
            },
            {
              _token: "a8830b9049e26a3b2cdd851d42a02b97",
              objectVersionNumber: 1,
              code: "SYS.TIME_ZONE",
              codeId: 10009,
              codeValues: null,
              description: "租户9",
              type: "USER",
              enabledFlag: "Y",
              parentCodeId: null,
              parentCodeDescription: null,
            },
            {
              _token: "11cb91cfc0d1d59335ba6607e42c640c",
              objectVersionNumber: 1,
              code: "SYS.USER_STATUS",
              codeId: 10010,
              codeValues: null,
              description: "租户10",
              type: "USER",
              enabledFlag: "Y",
              parentCodeId: null,
              parentCodeDescription: null,
            },
            {
              _token: "31cb91cfc0d1d59335ba6607e42c640c",
              objectVersionNumber: 1,
              code: "SYS.USER_STATUS11",
              codeId: 10011,
              codeValues: null,
              description: "租户11",
              type: "USER",
              enabledFlag: "Y",
              parentCodeId: null,
              parentCodeDescription: null,
            },
            {
              _token: "12cb91cfc0d1d59335ba6607e42c640c",
              objectVersionNumber: 1,
              code: "SYS.USER_STATUS12",
              codeId: 10012,
              codeValues: null,
              description: "租户12",
              type: "USER",
              enabledFlag: "Y",
              parentCodeId: null,
              parentCodeDescription: null,
            },
            {
              _token: "13cb91cfc0d1d59335ba6607e42c640c",
              objectVersionNumber: 1,
              code: "SYS.USER_STATUS13",
              codeId: 10013,
              codeValues: null,
              description: "租户13",
              type: "USER",
              enabledFlag: "Y",
              parentCodeId: null,
              parentCodeDescription: null,
            },
            {
              _token: "14cb91cfc0d1d59335ba6607e42c640c2",
              objectVersionNumber: 1,
              code: "SYS.USER_STATUS14",
              codeId: 10014,
              codeValues: null,
              description: "租户14",
              type: "USER",
              enabledFlag: "Y",
              parentCodeId: null,
              parentCodeDescription: null,
            },
            {
              _token: "15cb91cfc0d1d59335ba6607e42c640c",
              objectVersionNumber: 1,
              code: "SYS.USER_STATUS15",
              codeId: 10015,
              codeValues: null,
              description: "租户15",
              type: "USER",
              enabledFlag: "Y",
              parentCodeId: null,
              parentCodeDescription: null,
            },
            {
              _token: "16cb91cfc0d1d59335ba6607e42c640c",
              objectVersionNumber: 1,
              code: "SYS.USER_STATUS16",
              codeId: 10016,
              codeValues: null,
              description: "租户16",
              type: "USER",
              enabledFlag: "Y",
              parentCodeId: null,
              parentCodeDescription: null,
            },
            {
              _token: "17cb91cfc0d1d59335ba6607e42c640c",
              objectVersionNumber: 1,
              code: "SYS.USER_STATUS17",
              codeId: 10017,
              codeValues: null,
              description: "租户17",
              type: "USER",
              enabledFlag: "Y",
              parentCodeId: null,
              parentCodeDescription: null,
            },
            {
              _token: "18cb91cfc0d1d59335ba6607e42c640c",
              objectVersionNumber: 1,
              code: "SYS.USER_STATUS18",
              codeId: 10018,
              codeValues: null,
              description: "租户18",
              type: "USER",
              enabledFlag: "Y",
              parentCodeId: null,
              parentCodeDescription: null,
            },
            {
              _token: "19cb91cfc0d1d59335ba6607e42c640c",
              objectVersionNumber: 1,
              code: "SYS.USER_STATUS19",
              codeId: 10019,
              codeValues: null,
              description: "租户19",
              type: "USER",
              enabledFlag: "Y",
              parentCodeId: null,
              parentCodeDescription: null,
            },
            {
              _token: "20cb91cfc0d1d59335ba6607e42c640c",
              objectVersionNumber: 1,
              code: "SYS.USER_STATUS20",
              codeId: 10020,
              codeValues: null,
              description: "租户20",
              type: "USER",
              enabledFlag: "Y",
              parentCodeId: null,
              parentCodeDescription: null,
            },
          ],
          totalCount: 20,
        };
      },
    },
  ],
};
